on:
  push:
    branches:
      - staging

jobs:
  mirror_job:
    runs-on: ubuntu-latest
    name: Adding changes added directly to staging to draft to keep in sync.
    steps:
    - name: Mirror action step
      id: mirror
      uses: google/mirror-branch-action@v1.0
      with:
        github-token: ${{ secrets.ACTION_TOKEN }}
        source: staging
        dest: draft
